application: 'mess-menu'
runtime: java
version: '1'
inbound_services:
- warmup
- xmpp_message
- mail
derived_file_type:
- java_precompiled
threadsafe: True
api_version: '1.0'
handlers:
- url: (/)
  static_files: __static__\1NewIndex.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/.*/)
  static_files: __static__\1NewIndex.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: /messmenu
  script: unused
  login: optional
  secure: optional
- url: /
  script: unused
  login: optional
  secure: optional
- url: /.*/
  script: unused
  login: optional
  secure: optional
- url: /_ah/.*
  script: unused
  login: optional
  secure: optional
- url: /_ah/spi/.*
  script: unused
  login: optional
  secure: optional
